### 1. 

En el archivo "logistic_regression_digits" hemos visto un ejemplo multiclase. Elimina todas las imágenes y etiqueta (label) cuyo valor del label no sea 1 o 9. Es decir, elimina todos los dígitos y quédate solo con los dígitos 1 y 9.

Ahora, realiza un entrenamiento con logistic regression con los nuevos datos:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema (probar al menos 2 diferentes)

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
from sklearn.datasets import load_digits
digits = load_digits() # 8x8 = 64 pixels  -- Very clean Dataset

In [27]:
df.columns

RangeIndex(start=0, stop=65, step=1)

In [3]:
df = pd.DataFrame(data= np.c_[digits['data'], digits['target']])
df

0    1     2     3     4     5    6    7    8    9   ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63   64  
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0  0.0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0  1.0  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0  2.0  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0  3.0  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0  4.0  
...   ...  ...   ...   ...   ...  ...  ...  ...  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0  9.0  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0  0.0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0  8.0  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0  9.0  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0  8.0  

[1797 rows x 65 columns]

In [4]:
df_1_9 = df[(df.iloc[:,64] == 1) | (df.iloc[:,64] == 9)].reset_index(drop=True)
df_1_9

0    1     2     3     4     5    6    7    8    9   ...   55   56   57  \
0    0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  11.0  12.0   0.0   0.0  0.0  0.0  0.0  2.0  ...  0.0  0.0  0.0   
2    0.0  0.0   0.0   0.0  14.0  13.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0   6.0  14.0   4.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
4    0.0  0.0   0.0   2.0  16.0  16.0  2.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...  ...   
357  0.0  0.0   5.0  14.0  11.0   8.0  0.0  0.0  0.0  4.0  ...  0.0  0.0  0.0   
358  0.0  0.0   6.0  12.0  12.0   6.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
359  0.0  0.0   4.0  14.0  15.0   6.0  0.0  0.0  0.0  5.0  ...  0.0  0.0  0.0   
360  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
361  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      58    59    60    61    62   63   64  
0    0.0  11.0  16.0  10.0   0.0  0.0  1.0  
1    9.0  12.0  13.0   3.0   0.0  0.0  9.0  
2    0.0   1.0  13.0  16.0   1.0  0.0  1.0  
3    7.0  16.0  16.0  13.0  11.0  1.0  9.0  
4    0.0   2.0  12.0  15.0   4.0  0.0  1.0  
..   ...   ...   ...   ...   ...  ...  ...  
357  7.0  15.0  12.0   5.0   0.0  0.0  9.0  
358  2.0  11.0  10.0   4.0   0.0  0.0  1.0  
359  4.0  13.0  15.0   9.0   0.0  0.0  9.0  
360  2.0  14.0  15.0   9.0   0.0  0.0  9.0  
361  5.0  12.0  16.0  12.0   0.0  0.0  9.0  

[362 rows x 65 columns]

In [5]:
X = np.array(df_1_9.iloc[:,:-1])
X

array([[ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0., 11., ...,  3.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  1.,  0.],
       ...,
       [ 0.,  0.,  4., ...,  9.,  0.,  0.],
       [ 0.,  0.,  4., ...,  9.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.]])

In [6]:
y = np.array(df_1_9.iloc[:,-1])
y

array([1., 9., 1., 9., 1., 9., 9., 9., 9., 1., 1., 1., 9., 1., 9., 1., 1.,
       1., 9., 1., 1., 9., 1., 9., 9., 9., 1., 9., 1., 9., 1., 9., 9., 9.,
       9., 1., 1., 1., 9., 1., 9., 1., 1., 1., 9., 1., 1., 9., 1., 9., 9.,
       1., 9., 1., 9., 1., 9., 9., 9., 9., 1., 1., 1., 9., 1., 9., 1., 1.,
       1., 9., 1., 1., 9., 1., 9., 9., 9., 1., 9., 1., 9., 1., 9., 9., 9.,
       9., 1., 1., 1., 9., 1., 9., 1., 1., 1., 9., 1., 1., 9., 1., 9., 9.,
       9., 1., 9., 1., 9., 1., 9., 9., 9., 9., 1., 1., 1., 9., 1., 9., 1.,
       1., 1., 9., 1., 1., 9., 1., 9., 9., 9., 1., 9., 1., 9., 1., 9., 9.,
       9., 9., 1., 1., 1., 9., 1., 9., 1., 1., 1., 9., 1., 1., 9., 1., 9.,
       9., 9., 1., 9., 1., 9., 1., 9., 9., 9., 9., 1., 1., 1., 9., 1., 9.,
       1., 1., 1., 9., 1., 1., 9., 1., 9., 9., 9., 1., 9., 1., 9., 1., 9.,
       9., 9., 9., 1., 1., 1., 9., 1., 9., 1., 1., 1., 9., 1., 1., 9., 1.,
       9., 9., 9., 1., 9., 1., 9., 1., 9., 9., 9., 9., 1., 1., 1., 9., 1.,
       9., 1., 1., 1., 9.

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

# np.array(df_1_9.iloc[:,:-1]) --> representa los arrays de números
# np.array(df_1_9.iloc[:,-1]) --> representa los targets

In [8]:
print('X_train:', X_train.shape)
print('X_test:', X_test.shape)
print('y_train:', y_train.shape)
print('y_test:', y_test.shape)

X_train: (325, 64)
X_test: (37, 64)
y_train: (325,)
y_test: (37,)


In [9]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression(max_iter=1000)
logisticRegr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [10]:
y_train[:5]

array([9., 1., 9., 1., 1.])

In [11]:
logisticRegr.predict(X_train[:5])

array([9., 1., 9., 1., 1.])

## Vemos que el modelo está bien entrenado para los primeros 5 dígitos...

In [12]:
y_test[:5]

array([9., 1., 1., 1., 1.])

In [13]:
logisticRegr.predict(X_test[:5])

array([9., 1., 1., 1., 1.])

## Además, probando los primeros 5 dígitos del conjunto de TEST, nuevamente observamos todos aciertos.

## Veamos ahora para un único dígito...

In [14]:
y_test[20]

9.0

In [15]:
logisticRegr.predict(X_test[20].reshape(1, -1))

array([9.])

In [16]:
logisticRegr.predict_proba(X_test[20].reshape(1, -1))


array([[5.02912093e-08, 9.99999950e-01]])

## Así se puede ver que tiene prácticamente un 100 % de seguridad que el dígito de la posición 20 es un "9"

In [17]:
y_test[0:10]

array([9., 1., 1., 1., 1., 9., 9., 9., 1., 9.])

In [18]:
logisticRegr.predict(X_test[0:10])

array([9., 1., 1., 1., 1., 9., 9., 9., 1., 9.])

In [19]:
logisticRegr.predict_proba(X_test[0:10])

array([[4.38143832e-09, 9.99999996e-01],
       [9.99986022e-01, 1.39784406e-05],
       [9.99998998e-01, 1.00155296e-06],
       [9.98785743e-01, 1.21425685e-03],
       [9.99998504e-01, 1.49568071e-06],
       [2.27938260e-08, 9.99999977e-01],
       [6.54787884e-04, 9.99345212e-01],
       [1.50452295e-03, 9.98495477e-01],
       [9.99999782e-01, 2.17783803e-07],
       [1.30231567e-02, 9.86976843e-01]])

In [20]:
logisticRegr.classes_

array([1., 9.])

## Midiendo la performance del modelo

In [21]:
score = logisticRegr.score(X_train, y_train) * 100
score

100.0

In [22]:
score = logisticRegr.score(X_test, y_test) * 100
score

100.0

### Tanto para el conjunto de TRAIN como para el conjunto de TEST se observa un score del 100%

## Matriz de confusión

In [23]:
import sklearn.metrics as metrics
predictions = logisticRegr.predict(X_test)
matriz_confusion = metrics.confusion_matrix(y_test, predictions)
print(matriz_confusion)

[[19  0]
 [ 0 18]]


### La matriz de confusión indica que hay 19 números "1", cuya predicción fue acertada, y 18 números "9" cuya predicción fue acertada. NO hubo errores.

## Una vez que estoy contento con mi modelo, entreno el modelo con todos los datos que tengo

In [24]:
logisticRegr.fit(X, y)

LogisticRegression(max_iter=1000)

In [25]:
y_pred = logisticRegr.predict(X)

In [26]:
logisticRegr.score(X, y)

1.0