# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [2]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_array[-1::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [7]:
my_array[-2:-4:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [15]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [39]:
array4 = np.arange(1,21).reshape(4,5)
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [41]:
array4.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [52]:
# También entiendo que se puede hacer con:

array4.transpose()

# No entiendo la diferencia entre una y otra.

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [61]:
array4[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [68]:
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [69]:
array4[0:3:2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [70]:
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [77]:
array4[0:3,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [79]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x

array(['Loro', 'Perro', 'Gato', 'Loro', 'Perro'], dtype='<U5')

In [84]:
x_bool = x == 'Loro'
print(x_bool)
print(x[x_bool])

[ True False False  True False]
['Loro' 'Loro']


In [86]:
print(x[x == 'Loro'])            # No sé si éstas serían las 2 maneras como se pretende que lo haga.

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [89]:
array9 = np.arange(20).reshape(2,5,2)
array9

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [148]:
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [91]:
array4[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [95]:
array11 = np.zeros(10)
array11

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
array11.itemsize

8

In [99]:
array11[3] = 1
print(array11)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [141]:
vector12 = np.arange(10,50)
print(vector12)
vector12.shape
vector12.ndim

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


1

In [142]:
print(vector12[:,np.newaxis])
vector12[:,np.newaxis].shape
vector12[:,np.newaxis].ndim

[[10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]]


2

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [144]:
vector13 = np.array([1,2,0,0,4,0])
vector13

array([1, 2, 0, 0, 4, 0])

In [152]:
np.nonzero(vector13)

(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [111]:
array14 = np.random.randint(100, size=(10,10))
array14

array([[94, 19, 24, 14, 33, 77, 96, 41,  6,  7],
       [55, 56, 93, 19, 14, 96, 19, 62, 29,  2],
       [84, 23, 35, 49, 99,  5, 69, 71, 77, 28],
       [83,  2, 54, 58, 49,  4, 66, 75, 95, 23],
       [95, 27, 15, 30, 70, 43, 23, 65,  1, 55],
       [32, 58, 47, 95, 14, 76, 45, 62, 36, 21],
       [57, 92, 75, 63, 22, 12, 37, 13, 33, 15],
       [57,  9, 19, 16, 12, 25, 74, 12, 45, 63],
       [98, 25, 35, 30, 30, 56, 32, 92,  2, 77],
       [41, 45,  0, 49, 72, 85, 46, 12, 35,  1]])

In [113]:
np.min(array14)

0

In [153]:
np.max(array14)

99

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [116]:
array15 = np.random.randint(30, size=30)
array15

array([13, 25, 20, 13, 11,  3,  3, 11,  4, 26, 18,  4, 23, 12, 16, 28, 27,
        8, 21, 20, 17,  1,  1, 20, 18,  0,  4, 11, 29, 23])

In [118]:
np.mean(array15)

14.333333333333334

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [126]:
array16 = np.zeros(30).reshape(5,6)
array16

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [129]:
array16[:5:4] = 1
array16[:,:6:5] = 1

In [130]:
array16

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [169]:
array17 = np.array([0,1])
array17_1 = np.hstack([array17, array17, array17, array17])
print(array17_1)
print('-----------------')
array17_2 = np.where(array17_1 == 0, 1, 0)
print(array17_2)
array17_final = np.vstack([(array17_1, array17_2)*4])
array17_final

[0 1 0 1 0 1 0 1]
-----------------
[1 0 1 0 1 0 1 0]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [178]:
array18 = np.array([[0,1],[1,0]])
print(array18)
array18 = np.tile(array18, (4, 4))
array18

[[0 1]
 [1 0]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [183]:
array19 = np.random.randint(10, size=(5,5))
print(array19)
(array19 - np.mean(array19)) / np.std(array19)

[[8 0 1 1 4]
 [9 6 8 3 4]
 [3 5 7 0 0]
 [8 3 9 7 5]
 [9 9 4 3 6]]


array([[ 1.03623037, -1.62077058, -1.28864546, -1.28864546, -0.29227011],
       [ 1.36835549,  0.37198013,  1.03623037, -0.62439522, -0.29227011],
       [-0.62439522,  0.03985501,  0.70410525, -1.62077058, -1.62077058],
       [ 1.03623037, -0.62439522,  1.36835549,  0.70410525,  0.03985501],
       [ 1.36835549,  1.36835549, -0.29227011, -0.62439522,  0.37198013]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [196]:
array20_1 = np.arange(11)
print(array20_1)
array20_2 = np.copy(array20_1)
array20_2[4:8] = -1
print(array20_2)
array20_3 = np.copy(array20_2)
array20_3 = np.where(array20_3 == -1, np.nan, array20_3)
print(array20_3)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0.  1.  2.  3. nan nan nan nan  8.  9. 10.]


## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [259]:
tablero = np.full((10,10), ' ')
print(tablero)

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [242]:
tablero[0:2,1] = 'O'
tablero[1,3:7] = 'O'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [238]:
tablero[1,3] = 'X'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' 'K' 'X' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' 'K' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' 'K' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' 'K' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' '-' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [257]:
tablero[0:4,9] = 'K'
print(tablero)

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' ' ' 'K' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' ' ' 'K' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' ' ' 'K' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' ' ' 'K' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'K' ' ' ' ' 'K' ' ']
 [' ' ' ' 'K' 'K' ' ' 'K' ' ' ' ' 'K' ' ']
 [' ' ' ' 'K' 'K' ' ' 'K' ' ' ' ' 'K' ' ']
 [' ' ' ' 'K' 'K' ' ' 'K' ' ' ' ' 'K' ' ']]


In [219]:
tablero[6,6] = '-'
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'X', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', '-', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [220]:
import random

In [260]:
print(tablero)

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [231]:
a = random.randint(0,9)
print(a)
b = random.randint(0,9)
print(b)
direccion = random.randint(1,4)             # 1. Norte, 2. Sur, 3. Este, 4. Oeste
print(direccion)
if direccion == 1:   # Va para arriba
    if a < 3:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE
    elif a == 3:
        tablero[a::-1,b] = '1a'
    elif a > 3:
        c = a - 4
        tablero[a:c:-1,b] = '1b'
if direccion == 2:   # Va para abajo
    if a <= 6:
        c = a + 4
        tablero[a:c,b] = '2a'
    elif a > 6:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE
if direccion == 3:   # Va para la derecha
    if b <= 6:    
        c = b + 4
        tablero[a,b:c] = '3a'
    elif b > 6:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE
if direccion == 4:   # Va para la izquierda
    if b < 3:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEE
    elif b == 3:
        tablero[a,b::-1] = '4a'
    elif b > 3:
        c = b - 4
        tablero[a,b:c:-1] = '4b'

0
6


In [307]:
tablero = np.full((10,10), ' ')
a = random.randint(0,9)
print('A:', a)
b = random.randint(0,9)
print('B:', b)
direccion = random.randint(1,4)             # 1. Norte, 2. Sur, 3. Este, 4. Oeste
print('Dirección:', direccion)
print('1. Norte, 2. Sur, 3. Este, 4. Oeste')


if direccion == 1:   # Va para arriba
    if a < 3:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE
    elif a == 3:
        tablero[a::-1,b] = 'O'
        print(tablero)
    elif a > 3:
        c = a - 4
        tablero[a:c:-1,b] = 'O'
        print(tablero)
elif direccion == 2:   # Va para abajo
    if a <= 6:
        c = a + 4
        tablero[a:c,b] = 'O'
        print(tablero)
    elif a > 6:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE
elif direccion == 3:   # Va para la derecha
    if b <= 6:    
        c = b + 4
        tablero[a,b:c] = 'O'
        print(tablero)
    elif b > 6:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE
elif direccion == 4:   # Va para la izquierda
    if b < 3:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEE
    elif b == 3:
        tablero[a,b::-1] = 'O'
        print(tablero)
    elif b > 3:
        c = b - 4
        tablero[a,b:c:-1] = 'O'
        print(tablero)

A: 4
B: 6
Dirección: 4
1. Norte, 2. Sur, 3. Este, 4. Oeste
[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
