# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

In [3]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_array[-1::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [5]:
my_array[-2:-4:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [6]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [7]:
array4 = np.arange(1,21).reshape(4,5)
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
array4.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [9]:
# También entiendo que se puede hacer con:

array4.transpose()

# No entiendo la diferencia entre una y otra.

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [10]:
array4[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [11]:
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
array4[0:3:2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [13]:
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
array4[0:3,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [15]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x

array(['Loro', 'Perro', 'Gato', 'Loro', 'Perro'], dtype='<U5')

In [16]:
x_bool = x == 'Loro'
print(x_bool)
print(x[x_bool])

[ True False False  True False]
['Loro' 'Loro']


In [17]:
print(x[x == 'Loro'])            # No sé si éstas serían las 2 maneras como se pretende que lo haga.

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [18]:
array9 = np.arange(20).reshape(2,5,2)
array9

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [19]:
array4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
array4[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [21]:
array11 = np.zeros(10)
array11

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
array11.itemsize

8

In [23]:
array11[3] = 1
print(array11)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [24]:
vector12 = np.arange(10,50)
print(vector12)
vector12.shape
vector12.ndim

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


1

In [25]:
print(vector12[:,np.newaxis])
vector12[:,np.newaxis].shape
vector12[:,np.newaxis].ndim

[[10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]
 [31]
 [32]
 [33]
 [34]
 [35]
 [36]
 [37]
 [38]
 [39]
 [40]
 [41]
 [42]
 [43]
 [44]
 [45]
 [46]
 [47]
 [48]
 [49]]


2

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [26]:
vector13 = np.array([1,2,0,0,4,0])
vector13

array([1, 2, 0, 0, 4, 0])

In [27]:
np.nonzero(vector13)

(array([0, 1, 4], dtype=int64),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [28]:
array14 = np.random.randint(100, size=(10,10))
array14

array([[54, 39, 16, 69, 99, 83, 80, 36, 27, 26],
       [ 6, 11, 11, 95, 16, 53, 40, 43, 83, 28],
       [24, 95, 59, 96, 58,  6, 54, 49, 28, 63],
       [56, 82, 45, 64, 91, 54, 95, 78, 37, 40],
       [71, 52, 47, 47, 25, 61, 81, 92,  5,  1],
       [37, 98, 98,  7, 16, 89, 71, 91, 60, 59],
       [54, 82, 49, 14, 52, 23,  2, 88, 30,  7],
       [96,  0, 90, 67, 64, 82,  3, 58, 64, 12],
       [ 1, 27, 86,  7,  3, 48, 37, 49,  7, 13],
       [41, 85, 69, 85, 86,  0, 51, 64, 80, 55]])

In [29]:
np.min(array14)

0

In [30]:
np.max(array14)

99

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [31]:
array15 = np.random.randint(30, size=30)
array15

array([28,  9, 11, 21, 22, 14, 16,  6, 12, 17,  4, 17,  9, 11, 12,  1, 28,
       21, 15, 21, 27, 19, 10, 17,  4,  9, 23, 12,  8,  2])

In [32]:
np.mean(array15)

14.2

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [33]:
array16 = np.zeros(30).reshape(5,6)
array16

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
array16[:5:4] = 1
array16[:,:6:5] = 1

In [35]:
array16

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [36]:
array17 = np.array([0,1])
array17_1 = np.hstack([array17, array17, array17, array17])
print(array17_1)
print('-----------------')
array17_2 = np.where(array17_1 == 0, 1, 0)
print(array17_2)
array17_final = np.vstack([(array17_1, array17_2)*4])
array17_final

[0 1 0 1 0 1 0 1]
-----------------
[1 0 1 0 1 0 1 0]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [37]:
array18 = np.array([[0,1],[1,0]])
print(array18)
array18 = np.tile(array18, (4, 4))
array18

[[0 1]
 [1 0]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [38]:
array19 = np.random.randint(10, size=(5,5))
print(array19)
(array19 - np.mean(array19)) / np.std(array19)

[[2 6 4 8 0]
 [6 2 2 8 4]
 [0 0 6 5 7]
 [2 4 3 4 7]
 [9 8 2 3 5]]


array([[-0.86662577,  0.65377032, -0.10642773,  1.41396836, -1.62682381],
       [ 0.65377032, -0.86662577, -0.86662577,  1.41396836, -0.10642773],
       [-1.62682381, -1.62682381,  0.65377032,  0.2736713 ,  1.03386934],
       [-0.86662577, -0.10642773, -0.48652675, -0.10642773,  1.03386934],
       [ 1.79406738,  1.41396836, -0.86662577, -0.48652675,  0.2736713 ]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [39]:
array20_1 = np.arange(11)
print(array20_1)
array20_2 = np.copy(array20_1)
array20_2[4:8] = -1
print(array20_2)
array20_3 = np.copy(array20_2)
array20_3 = np.where(array20_3 == -1, np.nan, array20_3)
print(array20_3)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -1 -1 -1 -1  8  9 10]
[ 0.  1.  2.  3. nan nan nan nan  8.  9. 10.]


## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [40]:
tablero = np.full((10,10), ' ')
print(tablero)

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [41]:
tablero[0:2,1] = 'O'
tablero[1,3:7] = 'O'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [42]:
np.any(tablero[4,2:5] == 'O')

False

In [43]:
tablero[1,3] = 'X'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'X' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [44]:
tablero[0:4,9] = 'K'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' 'O' ' ' 'X' 'O' 'O' 'O' ' ' ' ' 'K']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [45]:
tablero[6,6] = '-'
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'K'],
       [' ', 'O', ' ', 'X', 'O', 'O', 'O', ' ', ' ', 'K'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'K'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'K'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', '-', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [46]:
import random

In [47]:
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' 'O' ' ' 'X' 'O' 'O' 'O' ' ' ' ' 'K']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'K']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' '-' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [48]:
''' a = random.randint(0,9)
print(a)
b = random.randint(0,9)
print(b)
direccion = random.randint(1,4)             # 1. Norte, 2. Sur, 3. Este, 4. Oeste
print(direccion)
if direccion == 1:   # Va para arriba
    if a < 3:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE
    elif a == 3:
        tablero[a::-1,b] = '1a'
    elif a > 3:
        c = a - 4
        tablero[a:c:-1,b] = '1b'
if direccion == 2:   # Va para abajo
    if a <= 6:
        c = a + 4
        tablero[a:c,b] = '2a'
    elif a > 6:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE
if direccion == 3:   # Va para la derecha
    if b <= 6:    
        c = b + 4
        tablero[a,b:c] = '3a'
    elif b > 6:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE
if direccion == 4:   # Va para la izquierda
    if b < 3:
        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEE
    elif b == 3:
        tablero[a,b::-1] = '4a'
    elif b > 3:
        c = b - 4
        tablero[a,b:c:-1] = '4b' '''

" a = random.randint(0,9)\nprint(a)\nb = random.randint(0,9)\nprint(b)\ndireccion = random.randint(1,4)             # 1. Norte, 2. Sur, 3. Este, 4. Oeste\nprint(direccion)\nif direccion == 1:   # Va para arriba\n    if a < 3:\n        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE\n    elif a == 3:\n        tablero[a::-1,b] = '1a'\n    elif a > 3:\n        c = a - 4\n        tablero[a:c:-1,b] = '1b'\nif direccion == 2:   # Va para abajo\n    if a <= 6:\n        c = a + 4\n        tablero[a:c,b] = '2a'\n    elif a > 6:\n        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE\nif direccion == 3:   # Va para la derecha\n    if b <= 6:    \n        c = b + 4\n        tablero[a,b:c] = '3a'\n    elif b > 6:\n        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEEE\nif direccion == 4:   # Va para la izquierda\n    if b < 3:\n        pass # SE SALEEEEEEEEEEEEEEEEEEEEEEEE\n    elif b == 3:\n        tablero[a,b::-1] = '4a'\n    elif b > 3:\n        c = b - 4\n        tablero[a,b:c:-1] = '4b' "

In [52]:
import numpy as np
import random

In [53]:
tablero = np.full((10,10), ' ')
def Hundir_la_flota():
    contador = 0
    while True:
        a = random.randint(0,9)
        print('A:', a)
        b = random.randint(0,9)
        print('B:', b)
        direccion = random.randint(1,4)             # 1. Norte, 2. Sur, 3. Este, 4. Oeste
        print('Dirección:', direccion)
        print('1. Norte, 2. Sur, 3. Este, 4. Oeste')
        if direccion == 1:   # Va para arriba
            if a < 3:
                print('------------------------------------ AQUÍ SE SALIÓ DEL TABLERO')
                continue # SE SALE
            elif a == 3:
                if np.any(tablero[a::-1,b] == 'O'):
                    print('-------------------------------------Allí ya hay un barco !!')
                    continue # HAY BARCO EN ESE LUGAR
                else:
                    tablero[a::-1,b] = 'O'
                    return print(tablero)
            elif a > 3:
                c = a - 4
                if np.any(tablero[a:c:-1,b] == 'O'):
                    print('-------------------------------------Allí ya hay un barco !!')
                    continue # HAY BARCO EN ESE LUGAR
                else:
                    tablero[a:c:-1,b] = 'O'
                    return print(tablero)
        elif direccion == 2:   # Va para abajo
            if a <= 6:
                c = a + 4
                if np.any(tablero[a:c,b] == 'O'):
                    print('-------------------------------------Allí ya hay un barco !!')
                    continue # HAY BARCO EN ESE LUGAR
                else:
                    tablero[a:c,b] = 'O'
                    return print(tablero)
            elif a > 6:
                print('------------------------------------ AQUÍ SE SALIÓ DEL TABLERO')
                continue # SE SALE
        elif direccion == 3:   # Va para la derecha
            if b <= 6:    
                c = b + 4
                if np.any(tablero[a,b:c] == 'O'):
                    print('-------------------------------------Allí ya hay un barco !!')
                    continue # HAY BARCO EN ESE LUGAR
                else:
                    tablero[a,b:c] = 'O'
                    return print(tablero)
            elif b > 6:
                print('------------------------------------ AQUÍ SE SALIÓ DEL TABLERO')
                continue # SE SALE
        elif direccion == 4:   # Va para la izquierda
            if b < 3:
                print('------------------------------------ AQUÍ SE SALIÓ DEL TABLERO')
                continue # SE SALE
            elif b == 3:
                if np.any(tablero[a,b::-1] == 'O'):
                    print('-------------------------------------Allí ya hay un barco !!')
                    continue # HAY BARCO EN ESE LUGAR
                else:
                    tablero[a,b::-1] = 'O'
                    return print(tablero)
            elif b > 3:
                c = b - 4
                if np.any(tablero[a,b:c:-1] == 'O'):
                    print('-------------------------------------Allí ya hay un barco !!')
                    continue # HAY BARCO EN ESE LUGAR
                else:
                    tablero[a,b:c:-1] = 'O'
                    return print(tablero)

## Al Mini Hundir la Flota le faltaría que el barco de tamaño 4 que se ingresa en forma aleatoria tampoco pueda ingresarse pegado a los otros 2 barcos existentes.

In [54]:
Hundir_la_flota()

A: 9
B: 5
Dirección: 3
1. Norte, 2. Sur, 3. Este, 4. Oeste
[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' 'O' 'O' 'O' 'O' ' ']]
