In [1]:
import numpy as np

In [5]:
data = np.random.randn(2,3)
data

array([[-1.60168351, -1.36396948, -0.1966535 ],
       [-0.0273779 , -1.77987579,  2.4377279 ]])

In [6]:
data * 10

array([[-16.01683509, -13.63969485,  -1.96653499],
       [ -0.27377901, -17.79875788,  24.37727903]])

In [7]:
data + data

array([[-3.20336702, -2.72793897, -0.393307  ],
       [-0.0547558 , -3.55975158,  4.87545581]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.ones_like(data)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.empty(5)

array([2.12199579e-314, 4.95269391e+223, 4.86160596e-321, 6.95208261e-310,
       9.78375159e+199])

In [23]:
np.zeros((3,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
np.empty((2,3,4))

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         1.37961438e-306],
        [1.89146896e-307, 7.56571288e-307, 4.00544531e-307,
         1.11261095e-306],
        [3.56043054e-307, 1.37961641e-306, 2.22518251e-306,
         1.33511969e-306]],

       [[1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
         1.69119330e-306],
        [1.37962320e-306, 6.89812281e-307, 1.24611674e-306,
         6.23060065e-307],
        [1.42420481e-306, 1.95818994e-306, 8.90070286e-308,
         2.56765117e-312]]])

In [25]:
np.empty([2,3,4])

array([[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
         1.37961438e-306],
        [1.89146896e-307, 7.56571288e-307, 4.00544531e-307,
         1.11261095e-306],
        [3.56043054e-307, 1.37961641e-306, 2.22518251e-306,
         1.33511969e-306]],

       [[1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
         1.69119330e-306],
        [1.37962320e-306, 6.89812281e-307, 1.24611674e-306,
         6.23060065e-307],
        [1.42420481e-306, 1.95818994e-306, 8.90070286e-308,
         2.56765117e-312]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
np.full_like(data,3,'int64')

array([[3, 3, 3],
       [3, 3, 3]], dtype=int64)

In [47]:
np.eye(4,3,dtype='int64')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int64)

In [46]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
un_array = np.array([2,3,4])
un_array.dtype

dtype('int32')

In [57]:
un_array_float = un_array.astype('float64')
un_array_float.dtype

dtype('float64')

In [58]:
un_array_float

array([2., 3., 4.])

In [69]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [67]:
numeric_strings.astype('float')

array([ 1.25, -9.6 , 42.  ])

In [73]:
numeric_strings.astype('float')
print(numeric_strings)

[b'1.25' b'-9.6' b'42']


In [74]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [75]:
calibers.dtype

dtype('float64')

In [85]:
int_array = np.arange(10)

In [86]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
mat1 = np.array([[1., 2., 3.], [4., 5., 6.],[4., 5., 6.],[4., 5., 6.]])

In [96]:
mat1.ndim

2

In [97]:
mat1.shape

(4, 3)

In [100]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [99]:
arr < arr2

array([[False,  True, False],
       [ True, False,  True]])

In [119]:
arr = np.arange(10)

In [120]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
arr[4]

4

In [122]:
arr[5:8]

array([5, 6, 7])

In [123]:
arr[5:8] = 12

In [124]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [125]:
arr_slice = arr[5:9]

In [126]:
arr_slice

array([12, 12, 12,  8])

In [127]:
arr_slice[1] = 1234

In [128]:
arr

array([   0,    1,    2,    3,    4,   12, 1234,   12,    8,    9])

In [129]:
arr_slice[:] = 64

In [130]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64, 64,  9])

In [131]:
pedazo_copiado = arr[5:8].copy()

In [132]:
pedazo_copiado

array([64, 64, 64])

In [133]:
pedazo_copiado[1:3] = 33

In [134]:
pedazo_copiado

array([64, 33, 33])

In [135]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64, 64,  9])

In [136]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [137]:
arr2d[2]

array([7, 8, 9])

In [138]:
arr2d[2][0]

7

In [140]:
arr2d[2,0]           # SE PUEDE PASAR CON COMAAAAA !!!!!!!!!!!!!

7


In [148]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [149]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [150]:
arr3d.shape

(2, 2, 3)

In [151]:
arr3d[0]            

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
arr2d.shape

(3, 3)

In [164]:
mima = np.array([[2,3,4],[5,6,7]])

In [167]:
mima.shape

(2, 3)

In [168]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [171]:
arr2d[:2,2]

array([3, 6])

In [183]:
arr2d[2:,:].shape

(1, 3)

In [189]:
arr2d[1,:2]

array([4, 5])

In [196]:
arr2d[1,2:].shape

(1,)

In [191]:
arr2d[1:2,:2]

array([[4, 5]])

In [195]:
arr2d[1:2,:2].shape

(1, 2)

In [197]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [198]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [199]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [200]:
data = np.random.randn(7, 4)

In [201]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [202]:
data

array([[-0.46943249, -0.69678854, -0.34023709, -2.12222135],
       [ 0.7292947 , -1.66621358, -0.93996378,  0.57824776],
       [-0.48609452,  0.60954086,  1.53732612,  0.69546068],
       [-0.01616492,  0.26098323, -0.67544149,  0.20738264],
       [-0.08912436, -1.15932439,  0.96363691, -0.94896219],
       [-1.28700054,  0.54118684,  0.66310261,  0.62302531],
       [-0.24484239,  0.26095983,  0.69096851,  1.17019437]])

In [203]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [204]:
data[names=='Bob']      #Primera y cuarta fila

array([[-0.46943249, -0.69678854, -0.34023709, -2.12222135],
       [-0.01616492,  0.26098323, -0.67544149,  0.20738264]])

In [205]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [206]:
data [~(names == 'Bob')]

array([[ 0.7292947 , -1.66621358, -0.93996378,  0.57824776],
       [-0.48609452,  0.60954086,  1.53732612,  0.69546068],
       [-0.08912436, -1.15932439,  0.96363691, -0.94896219],
       [-1.28700054,  0.54118684,  0.66310261,  0.62302531],
       [-0.24484239,  0.26095983,  0.69096851,  1.17019437]])

In [207]:
data

array([[-0.46943249, -0.69678854, -0.34023709, -2.12222135],
       [ 0.7292947 , -1.66621358, -0.93996378,  0.57824776],
       [-0.48609452,  0.60954086,  1.53732612,  0.69546068],
       [-0.01616492,  0.26098323, -0.67544149,  0.20738264],
       [-0.08912436, -1.15932439,  0.96363691, -0.94896219],
       [-1.28700054,  0.54118684,  0.66310261,  0.62302531],
       [-0.24484239,  0.26095983,  0.69096851,  1.17019437]])

In [208]:
data[data<0] = 0

In [209]:
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.7292947 , 0.        , 0.        , 0.57824776],
       [0.        , 0.60954086, 1.53732612, 0.69546068],
       [0.        , 0.26098323, 0.        , 0.20738264],
       [0.        , 0.        , 0.96363691, 0.        ],
       [0.        , 0.54118684, 0.66310261, 0.62302531],
       [0.        , 0.26095983, 0.69096851, 1.17019437]])

In [211]:
data[names != 'Joe'] = 7

In [212]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.7292947 , 0.        , 0.        , 0.57824776],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.54118684, 0.66310261, 0.62302531],
       [0.        , 0.26095983, 0.69096851, 1.17019437]])

In [220]:
arr = np.arange(32).reshape((8,4))

In [221]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [222]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]        # La primer lista corresponde a las filas y la segunda a su interseccion con la columna                                                      respectivamente      

array([ 4, 23, 29, 10])

In [223]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]     # De esta forma (ver ":"), agarro, de las filas de la primera lista, TODOS los                                                   elementos, en el orden que indica la segunda lista

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [224]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [229]:
arr.T             # Para TRASPONER una matriz

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [231]:
arr = np.random.randn(6, 3)
arr

array([[ 0.37469764,  0.85854845,  0.36487646],
       [ 0.14041033, -0.47823271, -0.95727635],
       [ 0.06599385,  0.71155525,  1.56416503],
       [ 0.9093771 ,  0.03553733, -0.91026971],
       [ 1.78702085,  1.02451893, -0.23036045],
       [-0.56774789, -0.26106154, -0.5687263 ]])

In [235]:
np.dot(arr.T,arr)               # Multiplicar la TRASPUESTA de una matriz por su matriz

array([[ 4.50721645,  2.31287619, -0.81101207],
       [ 2.31287619,  2.5911779 ,  1.76417018],
       [-0.81101207,  1.76417018,  4.70123156]])

In [237]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [261]:
arr.transpose((1,0,2))                # Cambia de lugar los ejes... En este caso, cambia el eje 1 por el eje 0 ... el eje 2                                            queda en el mismo lugar

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [252]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [260]:
arr.swapaxes(1,2)                # Igual que la funcion anterior (traspose), elijo CUALES 2 EJES CAMBIAR DE LUGAR

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [272]:
x = np.random.randn(8)
x

array([ 1.38258933, -0.08226019,  1.47115835,  0.60578694, -0.91856021,
        1.06885494,  0.91243932, -2.0022529 ])

In [265]:
y = np.random.randn(8)
y

array([-0.05832897, -1.73304186, -1.78848062,  0.49809825, -0.87876137,
       -0.70244217, -2.53194174, -1.06544226])

In [273]:
np.maximum(x,y)              # Valor máximo para cada elemento de dos matrices de igual tamaño

array([ 1.38258933, -0.08226019,  1.47115835,  0.60578694, -0.87876137,
        1.06885494,  0.91243932, -1.06544226])

In [275]:
arr = np.random.randn(7) * 5
arr

array([-5.81646155, -4.24621359,  2.86025664, -4.81834416, -2.40289575,
       -2.18500149, -2.82945668])

In [276]:
np.modf(arr)            # Devuelve una matriz con el entero y otra con el resto de cada valor de la matriz dada... Como se ve abajo, se                              puede almacenar cada matriz en una nueva

(array([-0.81646155, -0.24621359,  0.86025664, -0.81834416, -0.40289575,
        -0.18500149, -0.82945668]),
 array([-5., -4.,  2., -4., -2., -2., -2.]))

In [278]:
resto, entero = np.modf(arr)

In [279]:
resto

array([-0.81646155, -0.24621359,  0.86025664, -0.81834416, -0.40289575,
       -0.18500149, -0.82945668])

In [280]:
entero

array([-5., -4.,  2., -4., -2., -2., -2.])

In [292]:
points = np.arange(-5, 5, 1)
points

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [295]:
x,y = np.meshgrid(points,points)

In [300]:
x

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [297]:
y

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [305]:
z = np.sqrt(x**2 + y**2)                     # Andá a saber qué mierda hizo
z

array([[7.07106781, 6.40312424, 5.83095189, 5.38516481, 5.09901951,
        5.        , 5.09901951, 5.38516481, 5.83095189, 6.40312424],
       [6.40312424, 5.65685425, 5.        , 4.47213595, 4.12310563,
        4.        , 4.12310563, 4.47213595, 5.        , 5.65685425],
       [5.83095189, 5.        , 4.24264069, 3.60555128, 3.16227766,
        3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [5.38516481, 4.47213595, 3.60555128, 2.82842712, 2.23606798,
        2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.        , 4.        , 3.        , 2.        , 1.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.38516481, 4.47213595, 3.6055512

In [318]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])      # Para cada TRUE, agrego el valor de XARR, sino, agrego el de YARR
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [319]:
result = np.where(cond, xarr, yarr)       # WHERE es como el IF y ELSE   (condicion, valor if, valor else)

In [320]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

## Sirve para esto

In [328]:
arr = np.random.randn(4, 4)
arr

array([[ 1.23217312,  0.62717667,  1.09396427,  0.53421075],
       [ 1.0987094 , -0.40707946,  0.34887451, -2.10013078],
       [-0.71824906,  0.55959088,  1.26724964,  0.48838762],
       [ 0.23105379,  0.84493263, -0.2053023 ,  1.05211202]])

In [329]:
arr > 0

array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [False,  True,  True,  True],
       [ True,  True, False,  True]])

In [341]:
np.where(arr > 0, 1, 2)            # Aplicando la condicion, a los TRUE les pongo 1 y a los FALSE les pongo 2.

array([[1, 1, 1, 1],
       [1, 2, 1, 2],
       [2, 1, 1, 1],
       [1, 1, 2, 1]])

## tambien puedo pasar todos los valores que cumplan una condicion a lo que yo quiera, y dejar el resto de la matriz igual

In [343]:
arr

array([[ 1.23217312,  0.62717667,  1.09396427,  0.53421075],
       [ 1.0987094 , -0.40707946,  0.34887451, -2.10013078],
       [-0.71824906,  0.55959088,  1.26724964,  0.48838762],
       [ 0.23105379,  0.84493263, -0.2053023 ,  1.05211202]])

In [344]:
np.where(arr > 0, 3, arr)            # Los valores positivos (>0), los transformo en un 3... El resto de la matriz queda igual.

array([[ 3.        ,  3.        ,  3.        ,  3.        ],
       [ 3.        , -0.40707946,  3.        , -2.10013078],
       [-0.71824906,  3.        ,  3.        ,  3.        ],
       [ 3.        ,  3.        , -0.2053023 ,  3.        ]])

In [352]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [359]:
arr.sum()

66

In [360]:
np.sum(arr)

66

In [361]:
arr.mean()

5.5

In [362]:
np.mean(arr)

5.5

## Una cosa que puedo hacer con la funcion "mean" y la matriz de arriba...

In [363]:
arr.mean(axis=0)       # Te da la media para cada columna (avanzando sobre el eje Y)

array([4.5, 5.5, 6.5])

In [364]:
arr.mean(axis=1)       # Te da la media para cada fila (avanzando sobre el eje X)

array([ 1.,  4.,  7., 10.])

## La funcion CUMSUM me sirve para ir sumando valores que se van acumulando... ver ejemplo..

In [381]:
arr = np.array((0,1,2,3,4,5,6,7,8))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [382]:
np.cumsum(arr)      # Valores acumulados

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

## Lo mismo se puede hacer para matrices de más de una dimensión... y para cada eje de ellas.

In [386]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [377]:
acum1 = arr.cumsum(axis=0)       # Valores acumulados en vertical (a lo largo del eje Y)
acum1

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [378]:
acum2 = arr.cumsum(axis=1)       # Valores acumulados en horizontal (a lo largo del eje X)
acum2

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

## De igual forma, se puede hacer el PPRODUCTOO ACUMULADO utilizando la funcion .cumprod

In [387]:
arr.cumprod(axis=0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]], dtype=int32)

In [388]:
arr = np.random.randn(100)
arr

array([-0.10526114, -0.04238335,  1.14142953,  0.66541743, -0.0510828 ,
       -0.36319226,  0.37990787, -0.64217497, -2.22859696, -0.56932623,
       -1.12080789, -0.33547315,  0.06531459,  0.12384887,  0.27560449,
        0.3369017 ,  0.73476851,  1.4386272 ,  2.68482916,  1.35525315,
       -2.15710587, -0.29481831,  0.70154449, -0.96785332, -0.16970944,
       -0.41739272,  0.40112907,  0.10138609, -1.02092193,  0.94631136,
        0.39442944, -0.53512343,  0.6695031 , -1.91187776, -1.63035886,
       -0.16462008, -0.82076903, -1.58291009,  0.80194315,  1.37416612,
       -0.6861646 , -0.38526315, -0.34867313,  1.00854373,  1.0923479 ,
       -1.13428469, -0.65030999, -0.45745621, -0.96608522, -0.09635464,
       -0.92572397,  0.09890832, -0.76528466, -0.14456745, -0.58133312,
       -1.19027322,  0.26877974,  0.60793082,  1.41874744,  0.17129164,
        1.4765624 , -1.34131475, -0.53940259,  0.7829542 , -0.6291611 ,
       -0.86627256, -0.99296789,  0.51758058, -0.52060025,  0.53

In [398]:
(arr>2).sum()          # CUENTA CUANTOS VALORES CUMPLEN CON LA CONDICION

1

## Comprobar si una matriz tiene TRUE o FALSE

In [400]:
bools = np.array([False, False, True, False])

In [402]:
bools.any()      # ALGUNO ES TRUE ??

True

In [403]:
bools.all()      # TODOS SON TRUE ??

False

## Método SORT para ordenar matrices

In [406]:
arr = np.random.randn(6)
arr

array([-0.19584967,  0.37231323,  1.22561929,  0.04823609,  0.51736209,
       -0.12312929])

In [417]:
arr.sort()
arr

array([[-1.59298411, -1.30683706, -1.12346701,  0.18668772,  0.98407034],
       [-0.93785383, -0.61796528, -0.20904981,  0.30994763,  0.81623434],
       [-2.7390733 , -0.90203157, -0.23312576,  0.24567712,  1.34110219]])

## Tambien se puede usar para ordenar UNA DIMENSION de una matriz MULTIDIMENSIONAL 

In [411]:
arr = np.random.randn(3,5)
arr

array([[-1.30683706,  0.18668772, -1.59298411,  0.98407034, -1.12346701],
       [ 0.81623434, -0.20904981, -0.93785383, -0.61796528,  0.30994763],
       [-0.23312576, -2.7390733 ,  0.24567712,  1.34110219, -0.90203157]])

In [419]:
arr.sort(axis=1)      # De esta forma ordeno CADA FILA de menor a mayor...


   # De igual forma funciona para ordenar las columnas poniendo 0 en lugar de 1 (se puede omitir "axis")

In [420]:
arr

array([[-1.59298411, -1.30683706, -1.12346701,  0.18668772,  0.98407034],
       [-0.93785383, -0.61796528, -0.20904981,  0.30994763,  0.81623434],
       [-2.7390733 , -0.90203157, -0.23312576,  0.24567712,  1.34110219]])

## el método UNIQUE es similar a un SORTED(SET)... te devuelve el valor en la matriz una unica vez y ORDENADOS

In [421]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


In [423]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [426]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [424]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [425]:
np.unique(ints)

array([1, 2, 3, 4])

## multiplicar matrices

In [428]:
 x = np.array([[1., 2., 3.], [4., 5., 6.]])
 x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [441]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [432]:
x.dot(y)                # Es lo mismo que poner np.doy(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [435]:
z = np.ones(4)
z

array([1., 1., 1., 1.])

In [436]:
x.dot(z)    # SI LOS TAMAÑOS DE LAS MATRICES NO SON ADECUADOS... NO SE PUEDEN MULTIPLICARRRR

ValueError: shapes (2,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)